//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vakhitova_GlazkiSave
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public int AgentTypeID { get; set; }

        public string AgentTypeName
        {
            get
            {
                return AgentType.Title;
            }

        }

        public string Title { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public int Priority { get; set; }
        public string DirectorName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
    
        public int SalesForYear
        {
            get
            {
                int sales = 0;

                foreach (ProductSale productSale in ProductSale)
                {
                    TimeSpan differenceWithoutTime = DateTime.Today.Date - productSale.SaleDate.Date;

                    //if ((int)differenceWithoutTime.TotalDays <= 365)
                        //везде выдаст 0 тк даты оч старые
                        //поэтому сделаем без учета дат
                        sales += productSale.ProductCount;
                }

                return sales;
            }
        }

        public decimal Sales //продажи агента - суммируем все его стоимости
            // предварительно их посчитали как новое поле в ProductSale
        {
            get
            {
                decimal sales = 0;

                foreach (ProductSale productSale in ProductSale)
                {
                    sales += productSale.Stoimost;
                }

                return sales;
            }
        }

        public int Discount
        {
            get
            {
                if (this.Sales >= 500000)
                    return 25;

                if (this.Sales >= 150000)
                    return 20;

                if (this.Sales >= 50000)
                    return 10;

                if (this.Sales >= 10000)
                    return 5;

                return 0;
            }
        }

        public string FonStyle
        {
            get
            {
                if (Discount >= 25)
                    //ничего не увидим тк макс скидка 10 процентов
                    //надо поменять данные в бд
                    return "LightGreen";

                else
                    return "White";
            }
        }


        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
